// <auto-generated />
using CoreWebApp2.Models.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CoreWebApp2.Migrations
{
    [DbContext(typeof(SitesContext))]
    [Migration("20180603120931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("CoreWebApp2.Models.Sql.SearchedItem", b =>
                {
                    b.Property<int>("RowID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SearchedWord")
                        .IsRequired();

                    b.Property<int>("count");

                    b.HasKey("RowID");

                    b.ToTable("SearchedItems");
                });

            modelBuilder.Entity("CoreWebApp2.Models.Sql.SitesDB", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseUrl")
                        .IsRequired();

                    b.Property<string>("ImageAttribute")
                        .IsRequired()
                        .HasColumnName("ImageAttribute")
                        .HasColumnType("varchar");

                    b.Property<string>("ImageChilds")
                        .IsRequired()
                        .HasColumnName("ImageChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("LinkAttribute")
                        .IsRequired()
                        .HasColumnName("LinkAttribute")
                        .HasColumnType("varchar");

                    b.Property<string>("LinkChilds")
                        .IsRequired()
                        .HasColumnName("LinkChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("LinkExtra")
                        .HasColumnName("LinkExtra")
                        .HasColumnType("varchar");

                    b.Property<string>("Logo_link")
                        .IsRequired();

                    b.Property<string>("NameAttribute");

                    b.Property<string>("NameChilds")
                        .HasColumnName("NameChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("PriceAttribute")
                        .HasColumnName("PriceAttribute")
                        .HasColumnType("varchar");

                    b.Property<string>("PriceChilds")
                        .HasColumnName("PriceChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("PriceChildsTwo")
                        .HasColumnName("PriceChildsTwo")
                        .HasColumnType("varchar");

                    b.Property<string>("RepatedItem")
                        .IsRequired();

                    b.Property<string>("SatisfactionAttribute")
                        .HasColumnName("SatisfactionAttribute")
                        .HasColumnType("varchar");

                    b.Property<string>("SatisfactionChilds")
                        .HasColumnName("SatisfactionChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("SearcUrlPart2")
                        .IsRequired();

                    b.Property<string>("SearchUrlPart1")
                        .IsRequired();

                    b.Property<string>("SellerAttribute")
                        .HasColumnName("SellerAttribute")
                        .HasColumnType("varchar");

                    b.Property<string>("SellerChilds")
                        .HasColumnName("SellerChilds")
                        .HasColumnType("varchar");

                    b.Property<string>("SiteName")
                        .IsRequired();

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
